version: '3'
services:
  local:
    build: .
    command: bundle exec jekyll serve --watch --force_polling --host=0.0.0.0
    volumes:
      - .:/website
    ports:
      - "4000:4000"

  remote:
    build: .
    environment:
      - JEKYLL_ENV=production
    command: bundle exec jekyll build
    volumes:
      - .:/website
    ports:
      - "4000:4000"

  cleanup:
    build: .
    environment:
      - JEKYLL_ENV=production
    command: rm -rf _site && rm -rf .sass-cache/
    volumes:
      - .:/website
    ports:
      - "4000:4000"
